// <auto-generated />
using System;
using FeedbackService.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FeedbackService.Migrations
{
    [DbContext(typeof(DBApplicationContext))]
    partial class DBApplicationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("FeedbackService.Models.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("DeliveryId")
                        .HasColumnType("int");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<int>("RestaurantId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ReviewDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Reviews");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DeliveryId = 1,
                            Message = "Det var godt nok noget dårlig mad mand!!!",
                            Rating = 1,
                            RestaurantId = 1,
                            ReviewDate = new DateTime(2022, 11, 30, 10, 3, 20, 440, DateTimeKind.Local).AddTicks(2850),
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            DeliveryId = 1,
                            Message = "Det var godt nok noget lækker mad mand!!!",
                            Rating = 5,
                            RestaurantId = 1,
                            ReviewDate = new DateTime(2022, 11, 30, 10, 3, 20, 440, DateTimeKind.Local).AddTicks(2893),
                            UserId = 2
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
